### ISSUE TITLE
'Module not found' error when using in angular app

### ISSUE THREAD

**Issue by mcenkar** [anseki/htmlclean#12]
Hi, when I want to use htmlclean in new angular app

```
import * as htmlclean from 'htmlclean';
```

And then `htmlclean(someCode)` it gives me error:

```
ERROR in ./node_modules/htmlclean/lib/htmlclean.js
Module not found: Error: Can't resolve './pathdata' in '...\node_modules\htmlclean\lib'
 @ ./node_modules/htmlclean/lib/htmlclean.js 23:13-34
...

ERROR in ./node_modules/htmlclean/lib/htmlclean.js
Module not found: Error: Can't resolve './phrasing-elements' in '...\node_modules\htmlclean\lib'
 @ ./node_modules/htmlclean/lib/htmlclean.js 21:24-54
...
```

**Comment by anseki** [comment]
Hi @mcenkar, thank you for the report.

The htmlclean was written for Node.js script. A client environment is not supported.
Why do you use the library in Angular app?

Also, if you really want to use the library in Angular app, you should configure the Angular rather than adding the `.json` to the paths in the source code.
It works by adding the `.json` to `resolve.extensions` for Webpack.
The version of Angular in your environment might support `ng eject` command to change `webpack.config.js` file.

**Comment by mcenkar** [comment]
I use it just in unit tests, as it fits my need for one case, not for production code. I'm aware of possibility of adding it to webpack configuration, just it's more hassle than adding extension to require. Surely it doesn't break anything to add extension?

**Comment by anseki** [comment]
Do you mean that another error comes by adding the `.json` to `resolve.extensions` for Webpack?

**Comment by mcenkar** [comment]
No, out of the box my app doesn't even have any webpack configuration. If I use `ng eject` (which was disabled BTW)

```
$ ng eject
The 'eject' command has been temporarily disabled, as it is not yet compatible with the new
angular.json format. The new configuration format provides further flexibility to modify the...
```

I will then have future hassle of maintaining it. I'd rather fix htmlclean or use my fork, or even switch to a different library. I'll let you close or merge PR.

[_However, to remove ambiguity, you should probably specify a file extension when requiring anything other than .js files._](https://medium.freecodecamp.org/requiring-modules-in-node-js-everything-you-need-to-know-e7fbd119be8)

**Comment by anseki** [comment]
I see.
Anyways, as I said, it's better that you don't use htmlclean in Angular app because it was written for Node.js script.

**Comment by mcenkar** [comment]
I am not.

**Comment by anseki** [comment]
If you really want to use the library in Angular app, it can be solved by `resolve.extensions`.

**Comment by mcenkar** [comment]
My preferred solution now is:
```
npm install mcenkar/htmlclean#ff4d50a5bcc8534384bf157d36aac81345eb7498 --save-dev
```

Again, #13 is for you to decide. I don't want to use `ng eject` and configure webpack if I can simply avoid it. Proposed fix doesn't break anything apart from maybe limiting you from renaming these JSON files to .JS. But they are JSON anyway.

**Comment by anseki** [comment]
Thank you for the proposal.
When you use a library for Node.js, it might require configuration for Webpack.
Anyway, I might change the paths in future version. Thank you. :smile:

So, could you close this issue because it was solved?

**Comment by anseki** [comment]
No reply came, therefore it seems that this issue was already solved.
Then I close this issue.
